# load required packages
library(Signac);library(Seurat);library(ensembldb);library(EnsDb.Mmusculus.v79);library(patchwork);library(RColorBrewer);library(stringr)
library(ChIPseeker);library("TxDb.Mmusculus.UCSC.mm10.knownGene");library("org.Mm.eg.db");library(BSgenome.Mmusculus.UCSC.mm10);
library(EnsDb.Mmusculus.v79);library(JASPAR2020);library(TFBSTools);library(motifmatchr)


# Generation peak heatmap from each group

for(i in levels(multi.joint)) {
  peak.list <- list()
  peak.list[[i]] <- AccessiblePeaks(multi.joiny, idents = i)
  peak.list[[i]] <- StringToGRanges(peak.list[[i]], sep = c("-", "-"))
  assign(paste("cell",".",i,sep = ""), peak.list[[i]])
  
  peak.list <- GenomicRanges::GRangesList(`CAP1 (gCAP)` = readPeakFile(`cell.CAP1 (gCAP)`),
                                        `CAP2 (aCAP)` = readPeakFile(`cell.CAP2 (aCAP)`),
                                        Artery = readPeakFile(cell.Artery),
                                        Venous = readPeakFile(cell.Venous),
                                        Lymphatics = readPeakFile(cell.Lymphatics),
                                        Pericyte = readPeakFile(cell.Pericyte),
                                        Fibroblast = readPeakFile(cell.Fibroblast),
                                        Myofibroblast = readPeakFile(cell.Myofibroblast),
                                        Matrixfibroblast = readPeakFile(cell.Matrixfibroblast))
library(scales)
color.use <- as.vector(hue_pal()(n=9))                                     
peakHeatmap(peak.list, TxDb = TxDb.Mmusculus.UCSC.mm10.knownGene, upstream=3000, downstream=3000, color=color.use)   

BigwigTrack('chr8-120800001-120810000',as.list(figtest),smooth = 200,type = "coverage", bigwig.scale = "separate", ymax = NULL, max.downsample = 3000,downsample.rate = 0.1) + scale_fill_discrete()
figtest <- list.files(pattern="*.bw")

# human ACDMPV data processing

library(ensembldb);library(EnsDb.Hsapiens.v86);library(BSgenome.Hsapiens.UCSC.hg38)
library(Signac);library(Seurat);library(ggplot2);library(scales);library(pheatmap)
library(JASPAR2020);library(TFBSTools);library(motifmatchr)

set.seed(1234)

acd5.counts <- Read10X_h5("~/acdonor/ACD5_Multiome_filtered_feature_bc_matrix.h5")
fragpath <- "~/acdonor/ACD5_Multiome_atac_fragments.tsv.gz"

# get gene annotations for hg38
edb <- EnsDb.Hsapiens.v86
seqlevelsStyle(edb) <- "UCSC"
annotations <- GetGRangesFromEnsDb(ensdb = edb)
genome(annotations) <- "hg38"

# create a Seurat object containing the RNA adata
acd5.joint <- CreateSeuratObject(
  counts = acd5.counts$`Gene Expression`,
  assay = "RNA"
)

# create ATAC assay and add it to the object
acd5.joint[["ATAC"]] <- CreateChromatinAssay(
  counts = acd5.counts$Peaks,
  sep = c(":", "-"),
  fragments = fragpath,
  annotation = annotations
)

# Quality control
DefaultAssay(acd5.joint) <- "ATAC"

acd5.joint <- NucleosomeSignal(acd5.joint)
acd5.joint <- TSSEnrichment(acd5.joint)

VlnPlot(
  object = acd5.joint,
  features = c("nCount_RNA", "nCount_ATAC", "TSS.enrichment", "nucleosome_signal"),
  ncol = 4,
  pt.size = 0
)

acd5.joint <- NucleosomeSignal(object = acd5.joint)
acd5.joint <- TSSEnrichment(acd5.joint, fast = FALSE)


# Joint UMAP visualization

# build a joint neighbor graph using both assays
acd5.joint <- FindMultiModalNeighbors(
  object = acd5.joint,
  reduction.list = list("pca", "lsi"), 
  dims.list = list(1:50, 2:40),
  modality.weight.name = "RNA.weight",
  verbose = TRUE
)

# build a joint UMAP visualization
acd5.joint <- RunUMAP(
  object = acd5.joint,
  nn.name = "weighted.nn",
  assay = "RNA",
  verbose = TRUE
)

DimPlot(acd5.joint, label = TRUE, repel = TRUE, reduction = "umap") + NoLegend()
DimPlot(acd5.joint, label = FALSE, repel = TRUE, reduction = "umap")

#process metadata
control.meta <- read.table('control.meta.txt', header = T, sep = "", dec = ".")
work.meta <- control.meta %>% separate(cell, c("sample","barcode"), sep = "_")
meta.110 <- work.meta[work.meta$sample == 'D110',]

# read count files
matrix_dir = "open/"
barcode.path <- paste0(matrix_dir, "barcodes.tsv.gz")
features.path <- paste0(matrix_dir, "features.tsv.gz")
matrix.path <- paste0(matrix_dir, "matrix.mtx.gz")
mat <- readMM(file = matrix.path)
mat.dgc <- as(mat, "dgCMatrix")
feature.names = read.delim(features.path, header = FALSE, stringsAsFactors = FALSE)
barcode.names = read.delim(barcode.path, header = FALSE, stringsAsFactors = FALSE)
rownames(mat.dgc) = as.vector(barcode.names$V1)
colnames(mat.dgc) = as.vector(feature.names$V1)

# hg19 to hg38
peaks.hg19 <- StringToGRanges(regions = paste0 ('chr', colnames(mat.dgc)), sep = c(":", "-"))
hg19tohg38 <- rtracklayer::import.chain("~/hg19ToHg38.over.chain")
peaks.hg38 <- rtracklayer::liftOver(x = peaks.hg19, chain = hg19tohg38)
names(peaks.hg38) <- colnames(mat.dgc)


control <- RunUMAP(object = control, reduction = 'lsi', dims = 2:30)
control <- FindNeighbors(object = control, reduction = 'lsi', dims = 2:30)
control <- FindClusters(object = control, verbose = FALSE, algorithm = 3)
DimPlot(object = control, label = TRUE) + NoLegend()

control <- RenameIdents(control, "alveolar_type_2" = 'Epithelial', "alveolar_type_1" = 'Epithelial', "club" = 'Epithelial',"ciliated" = 'Epithelial', "pulmonary_neuroendocrine" = 'Epithelial', "basal" = 'Epithelial')
control <- RenameIdents(control, "matrix_fibroblast_2" = 'Mesenchymal', "matrix_fibroblast_1" = 'Mesenchymal', "myofibroblast" = 'Mesenchymal',"pericyte" = 'Mesenchymal')
control <- RenameIdents(control, "capillary_endothelial_1" = 'Endothelial', "arterial_endothelial" = 'Endothelial', "capillary_endothelial_2" = 'Endothelial',"lymphatic_endothelial" = 'Endothelial')

Idents(control) <- factor(Idents(control), levels = c("AT1", "AT2", "Ciliated", "Endothelial", "Fibroblast", "Pericyte", "Matrixfibroblast"))

CoveragePlot(
  object = control,
  region = "chr16-86020001-86040001",
  annotation = F,
  peaks = F,
  ncol = 1
)

CoveragePlot(
  object = control,
  region = "chr16-86075001-86095001",
  annotation = F,
  peaks = F,
  ncol = 1
)

CoveragePlot(
  object = control,
  region = "chr16-86140001-86160001",
  annotation = F,
  peaks = F,
  ncol = 1
)

CoveragePlot(
  object = control,
  region = "chr16-86175001-86195001",
  annotation = F,
  peaks = F,
  ncol = 1
)

CoveragePlot(
  object = control,
  region = "chr16-86500001-86520001",
  annotation = F,
  peaks = F,
  ncol = 1
)
# PieDonut plot
library(ggplot2)
library(webr)
library(dplyr)
names(pie.data) <- c('Cluster','Group','Frequency')
require(plyr)
pie.data <- as.data.frame(table(Idents(fel.move),fel.move$orig.ident))
pie.data$Group <- mapvalues(pie.data$Group, from=c("FEL0","FEL1","FEL4"), to=c("WT","MT1","MT4"))

PieDonut(pie.data, aes(Cluster, Group, count = Frequency),labelposition = 5, labelpositionThreshold = 0.5, addPieLabel = False, addDonutLabel = False,showRatioDonut = F, showRatioPie = F,showPieName = F,use.labels = F)
PieDonut(pie.data, aes(Cluster, Group, count = Frequency),explode = 1,explodePie = T,explodeDonut = T,labelposition = 5, labelpositionThreshold = 0.5,addPieLabel = False, addDonutLabel = False,showRatioDonut = F, showRatioPie = F,showPieName = F,use.labels = F)
PieDonut(pie.data, aes(Cluster, Group, count = Frequency),start = 2.5*pi/2,explode = 4,explodePie = T,explodeDonut = T,labelposition = 5, labelpositionThreshold = 0.5,addPieLabel = False, addDonutLabel = False,showRatioDonut = F, showRatioPie = F,showPieName = F,use.labels = F)
# myofibroblast
fel.myo <- subset(fel.move,idents = 'Myofibroblast')
fel.myo <- subset(fel.myo,idents = c('5','7','11'),invert = T)
fel.myo <- subset(fel.myo,cells = cell.look,invert = T)

DimPlot(fel.myo, label = F,cols = c('blue','orange'),split.by = 'orig.ident') 
DimPlot(fel.myo, label = F,cols = c('blue','orange'))

FeaturePlot(fel.myo, features = c("Acta2","Crip2","Cdh11","Tpm2","Cox4i2",'Ptprd'), ncol = 3)
pie.myo <- data.frame(table(Idents(fel.myo),fel.myo$orig.ident))
names(pie.myo) <- c('Cluster','Group','Frequency')
pie.myo$Group <- mapvalues(pie.myo$Group,
from=c("FEL0","FEL1","FEL4"),
to=c("WT","MT1","MT4"))

pie.myo$Cluster <- mapvalues(pie.myo$Cluster, from=c("4","15"), to=c("VSMC","ASMC"))
ggdonutchart(pie.myo[c(1,3,5),],'Frequency',fill = 'Group',label = 'Group',color = 'white',palette = hue_pal(h = c(90, 270))(3)) + theme(legend.position = "none",legend.title=element_blank(),legend.text=element_text(size=0),axis.text.x =element_text(size=0))
ggdonutchart(pie.myo[c(2,4,6),],'Frequency',fill = 'Group',label = 'Group',color = 'white',palette = hue_pal(h = c(90, 270))(3)) + theme(legend.position = "bottom",legend.title=element_blank(),legend.text=element_text(size=15),axis.text.x =element_text(size=0))
fel.myo <- RenameIdents(fel.myo, "4" = 'VSMC', "15" = 'ASMC')
DimPlot(fel.myo, reduction = "umap",cells.highlight = cell.plot,cols.highlight = scales::hue_pal()(6)[1]) + NoLegend()

# Chimera single cell 
fel.work <- readRDS("~/acdata/fel.towork.rds")
fel.work <- RenameIdents(fel.work, "0" = "Endothelial", "3" = "Endothelial", "6" = "Endothelial", "10" = "AT1","11" = "AT2","4" = "Myofibroblast","15" = "Myofibroblast","1" = "Pericyte","5" = "Pericyte","7" = "Fibroblast","9" = "Fibroblast","2" = "Matrixfibroblast","8" = "Matrixfibroblast")
fel.work <- RenameIdents(fel.work, "AT1" = 'Epithelial', "AT2" = 'Epithelial')
Idents(fel.work) <- factor(Idents(fel.work), levels = c("Endothelial","Epithelial","Fibroblast", "Myofibroblast", "Matrixfibroblast", "Pericyte"))
VlnPlot(fel.work, features = 'Foxf1', pt.size = 0,split.by = 'orig.ident') + theme(legend.position = "none",axis.title.x = element_text(size=0),axis.title.y = element_text(size=0),axis.text.x = element_text(size=15),axis.text.y = element_text(size=15),strip.text.y = element_text(size = 15))

plots <- VlnPlot(subset(fel.work,idents = c('Endothelial','Fibroblast','Pericyte')), features = 'Foxf1', pt.size = 0,split.by = 'orig.ident') + NoLegend()
plots <- VlnPlot(subset(fel.work,idents = 'Endothelial'), features = 'Foxf1', pt.size = 0,split.by = 'orig.ident',cols = c("#F8766D", "#078992", "#B79F00")) + NoLegend()
plots <- VlnPlot(subset(fel.work,idents = 'Fibroblast'), features = 'Foxf1', pt.size = 0,split.by = 'orig.ident') + NoLegend()
plots <- VlnPlot(subset(fel.work,idents = 'Pericyte'), features = 'Foxf1', pt.size = 0,split.by = 'orig.ident') + NoLegend()
for(i in 1:length(plots)) {
  plots[[i]] <- plots[[i]] + geom_boxplot(width=0.1, color="black", alpha = 0.8,position = position_dodge(width = 0.9),outlier.colour = NA) + theme(legend.position = 'none')
}
plots

endothelial <- subset(fel.work,idents = 'Endothelial')
fibroblast <- subset(fel.work,idents = 'Fibroblast')
pericyte <- subset(fel.work,idents = 'Pericyte')

fe0 <- GetAssayData(subset(endothelial,subset = orig.ident == 'FEL0'),slot = 'data')
fe1 <- GetAssayData(subset(endothelial,subset = orig.ident == 'FEL1'),slot = 'data')
fe4 <- GetAssayData(subset(endothelial,subset = orig.ident == 'FEL4'),slot = 'data')

ff0 <- GetAssayData(subset(fibroblast,subset = orig.ident == 'FEL0'),slot = 'data')
ff1 <- GetAssayData(subset(fibroblast,subset = orig.ident == 'FEL1'),slot = 'data')
ff4 <- GetAssayData(subset(fibroblast,subset = orig.ident == 'FEL4'),slot = 'data')

fp0 <- GetAssayData(subset(pericyte,subset = orig.ident == 'FEL0'),slot = 'data')
fp1 <- GetAssayData(subset(pericyte,subset = orig.ident == 'FEL1'),slot = 'data')
fp4 <- GetAssayData(subset(pericyte,subset = orig.ident == 'FEL4'),slot = 'data')

fe0.mean <- mean(fe0[rownames(fe0) == 'Foxf1',])
fe1.mean <- mean(fe1[rownames(fe1) == 'Foxf1',])
fe4.mean <- mean(fe4[rownames(fe4) == 'Foxf1',])

ff0.mean <- mean(ff0[rownames(ff0) == 'Foxf1',])
ff1.mean <- mean(ff1[rownames(ff1) == 'Foxf1',])
ff4.mean <- mean(ff4[rownames(ff4) == 'Foxf1',])

fp0.mean <- mean(fp0[rownames(fp0) == 'Foxf1',])
fp1.mean <- mean(fp1[rownames(fp1) == 'Foxf1',])
fp4.mean <- mean(fp4[rownames(fp4) == 'Foxf1',])

library(scales)
for(i in 6:8){
  show_col(hue_pal()(i))
}
unique(ggplot_build(p)$data[[1]]$fill)
show_col(unique(ggplot_build(p)$data[[1]]$fill))

fel.work <- readRDS("~/fels.work.rds")
endothelial <- subset(fel.work,idents = 'Endothelial')
fibroblast <- subset(fel.work,idents = 'Fibroblast')
pericyte <- subset(fel.work,idents = 'Pericyte')
Idents(endothelial) <- 'orig.ident'
Idents(fibroblast) <- 'orig.ident'
Idents(pericyte) <- 'orig.ident'
fel1.endo <- FindMarkers(endothelial, ident.1 = 'FEL1',ident.2 = c('FEL0','FEL4'),logfc.threshold = 0.5,min.pct = 0.3)
fel4.fibro <- FindMarkers(fibroblast, ident.1 = 'FEL4',ident.2 = c('FEL0','FEL1'),logfc.threshold = 0.5,min.pct = 0.3)
fel4.peri <- FindMarkers(pericyte, ident.1 = 'FEL4',ident.2 = c('FEL0','FEL1'),logfc.threshold = 0.5,min.pct = 0.3)
