# R packages used
R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] EnsDb.Mmusculus.v79_2.99.0                motifmatchr_1.16.0                       
 [3] BSgenome.Mmusculus.UCSC.mm10_1.4.3        TFBSTools_1.32.0                         
 [5] JASPAR2020_0.99.10                        ChIPseeker_1.30.3                        
 [7] TxDb.Mmusculus.UCSC.mm10.knownGene_3.10.0 org.Mm.eg.db_3.14.0                      
 [9] patchwork_1.1.1                           BSgenome.Hsapiens.UCSC.hg38_1.4.4        
[11] BSgenome_1.62.0                           rtracklayer_1.54.0                       
[13] Biostrings_2.62.0                         XVector_0.34.0                           
[15] EnsDb.Hsapiens.v86_2.99.0                 ensembldb_2.18.2                         
[17] AnnotationFilter_1.18.0                   GenomicFeatures_1.46.3                   
[19] AnnotationDbi_1.56.2                      Biobase_2.54.0                           
[21] GenomicRanges_1.46.1                      GenomeInfoDb_1.30.0                      
[23] IRanges_2.28.0                            S4Vectors_0.32.3                         
[25] BiocGenerics_0.40.0                       scales_1.1.1                             
[27] dplyr_1.0.7                               stringr_1.4.0                            
[29] ggpubr_0.4.0                              ggplot2_3.3.5                            
[31] Signac_1.6.0.9005                         SeuratObject_4.0.4                       
[33] Seurat_4.1.0                             

loaded via a namespace (and not attached):
  [1] rappdirs_0.3.3                          SnowballC_0.7.0                        
  [3] scattermore_0.7                         R.methodsS3_1.8.1                      
  [5] tidyr_1.1.4                             bit64_4.0.5                            
  [7] R.utils_2.11.0                          irlba_2.3.5                            
  [9] DelayedArray_0.20.0                     data.table_1.14.2                      
 [11] rpart_4.1-15                            KEGGREST_1.34.0                        
 [13] RCurl_1.98-1.5                          generics_0.1.1                         
 [15] cowplot_1.1.1                           RSQLite_2.2.9                          
 [17] shadowtext_0.1.1                        RANN_2.6.1                             
 [19] future_1.23.0                           tzdb_0.2.0                             
 [21] bit_4.0.4                               enrichplot_1.14.2                      
 [23] spatstat.data_2.1-2                     xml2_1.3.3                             
 [25] httpuv_1.6.4                            SummarizedExperiment_1.24.0            
 [27] assertthat_0.2.1                        DirichletMultinomial_1.36.0            
 [29] viridis_0.6.2                           xfun_0.31                              
 [31] hms_1.1.1                               promises_1.2.0.1                       
 [33] fansi_0.5.0                             restfulr_0.0.13                        
 [35] progress_1.2.2                          caTools_1.18.2                         
 [37] dbplyr_2.1.1                            igraph_1.3.1                           
 [39] DBI_1.1.2                               htmlwidgets_1.5.4                      
 [41] sparsesvd_0.2                           spatstat.geom_2.3-1                    
 [43] purrr_0.3.4                             ellipsis_0.3.2                         
 [45] backports_1.4.1                         annotate_1.72.0                        
 [47] biomaRt_2.50.1                          deldir_1.0-6                           
 [49] MatrixGenerics_1.6.0                    vctrs_0.3.8                            
 [51] ROCR_1.0-11                             abind_1.4-5                            
 [53] cachem_1.0.6                            withr_2.4.3                            
 [55] ggforce_0.3.3                           sctransform_0.3.3                      
 [57] GenomicAlignments_1.30.0                treeio_1.18.1                          
 [59] prettyunits_1.1.1                       goftest_1.2-3                          
 [61] cluster_2.1.2                           DOSE_3.20.1                            
 [63] seqLogo_1.60.0                          ape_5.6-1                              
 [65] lazyeval_0.2.2                          crayon_1.4.2                           
 [67] pkgconfig_2.0.3                         slam_0.1-49                            
 [69] tweenr_1.0.2                            nlme_3.1-153                           
 [71] ProtGenerics_1.26.0                     rlang_1.0.2                            
 [73] globals_0.14.0                          lifecycle_1.0.1                        
 [75] miniUI_0.1.1.1                          filelock_1.0.2                         
 [77] BiocFileCache_2.2.0                     polyclip_1.10-0                        
 [79] matrixStats_0.61.0                      lmtest_0.9-39                          
 [81] Matrix_1.4-0                            aplot_0.1.2                            
 [83] ggseqlogo_0.1                           carData_3.0-4                          
 [85] boot_1.3-28                             zoo_1.8-9                              
 [87] ggridges_0.5.3                          png_0.1-7                              
 [89] viridisLite_0.4.0                       rjson_0.2.20                           
 [91] bitops_1.0-7                            R.oo_1.24.0                            
 [93] KernSmooth_2.23-20                      blob_1.2.2                             
 [95] qvalue_2.26.0                           parallelly_1.30.0                      
 [97] readr_2.1.1                             rstatix_0.7.0                          
 [99] gridGraphics_0.5-1                      ggsignif_0.6.3                         
[101] CNEr_1.30.0                             memoise_2.0.1                          
[103] magrittr_2.0.1                          plyr_1.8.6                             
[105] ica_1.0-2                               gplots_3.1.1                           
[107] zlibbioc_1.40.0                         scatterpie_0.1.7                       
[109] compiler_4.1.2                          tinytex_0.39                           
[111] BiocIO_1.4.0                            RColorBrewer_1.1-2                     
[113] plotrix_3.8-2                           fitdistrplus_1.1-6                     
[115] Rsamtools_2.10.0                        cli_3.1.0                              
[117] listenv_0.8.0                           pbapply_1.5-0                          
[119] MASS_7.3-54                             mgcv_1.8-38                            
[121] tidyselect_1.1.1                        stringi_1.7.6                          
[123] yaml_2.2.1                              GOSemSim_2.20.0                        
[125] ggrepel_0.9.1                           grid_4.1.2                             
[127] fastmatch_1.1-3                         tools_4.1.2                            
[129] future.apply_1.8.1                      parallel_4.1.2                         
[131] rstudioapi_0.13                         TFMPvalue_0.0.8                        
[133] TxDb.Hsapiens.UCSC.hg19.knownGene_3.2.2 lsa_0.73.2                             
[135] gridExtra_2.3                           farver_2.1.0                           
[137] Rtsne_0.15                              ggraph_2.0.5                           
[139] digest_0.6.29                           pracma_2.3.6                           
[141] shiny_1.7.1                             qlcMatrix_0.9.7                        
[143] Rcpp_1.0.7                              car_3.0-12                             
[145] broom_0.7.11                            later_1.3.0                            
[147] RcppAnnoy_0.0.19                        httr_1.4.2                             
[149] colorspace_2.0-2                        XML_3.99-0.8                           
[151] tensor_1.5                              reticulate_1.22                        
[153] splines_4.1.2                           uwot_0.1.11                            
[155] yulab.utils_0.0.4                       RcppRoll_0.3.0                         
[157] tidytree_0.3.8                          spatstat.utils_2.3-0                   
[159] graphlayouts_0.8.0                      ggplotify_0.1.0                        
[161] plotly_4.10.0                           xtable_1.8-4                           
[163] poweRlaw_0.70.6                         jsonlite_1.7.2                         
[165] ggtree_3.2.1                            tidygraph_1.2.0                        
[167] ggfun_0.0.5                             R6_2.5.1                               
[169] pillar_1.6.4                            htmltools_0.5.2                        
[171] mime_0.12                               glue_1.6.0                             
[173] fastmap_1.1.0                           BiocParallel_1.28.3                    
[175] codetools_0.2-18                        fgsea_1.20.0                           
[177] utf8_1.2.2                              lattice_0.20-45                        
[179] spatstat.sparse_2.1-0                   tibble_3.1.6                           
[181] curl_4.3.2                              leiden_0.3.9                           
[183] gtools_3.9.2                            GO.db_3.14.0                           
[185] survival_3.2-13                         docopt_0.7.1                           
[187] munsell_0.5.0                           DO.db_2.9                              
[189] GenomeInfoDbData_1.2.7                  reshape2_1.4.4                         
[191] gtable_0.3.0                            spatstat.core_2.3-2           
